Landing page
josh-hdz/my_portfolio pull request #3
Opened 2021-02-27 08:28 UTC by josh-hdz

2021-02-27 08:50 UTC, josh-hdz commented
Sorry for the gigantic pull request

2021-02-27 19:05 UTC, jmuzy-sps requested changes
Great job! Only a few minor comments, mostly about formatting, otherwise LGTM!

2021-02-27 19:05 UTC, jmuzy-sps commented on portfolio/src/main/webapp/index.html
> +              say that from everywhere. I've lived in two countries, four states,
Tab this over once so the line lines up with the rest of the paragraph.

Same thing on line 42

2021-02-27 19:05 UTC, jmuzy-sps commented on portfolio/src/main/webapp/index.html
> +<!-------------------------------Project SECOM START--------------------------->
Big +1 to adding comments throughout the code, this is great

2021-02-27 19:05 UTC, jmuzy-sps commented on portfolio/src/main/webapp/script.js
> +  } while(chosen == last);
Nice improvement to ensure that the same message doesn't show twice!

2021-02-27 19:05 UTC, jmuzy-sps commented on portfolio/src/main/webapp/style.css
> +Prussian blue -> 1D3557
Optional: Instead of writing the hex codes in a comment, you could create variables and set their value to the hex colors (https://www.w3schools.com/css/css3_variables.asp). That way, if you decide you want to change your color scheme later, you can just modify the value of the variable, and all the spots on your website that used that variable will be updated!

2021-02-27 19:05 UTC, jmuzy-sps commented on portfolio/src/main/webapp/style.css
> +  height: 32px;
Optional

At Google, we have this readability rule that css attributes should be alphabetized. This makes it easier to find an attribute if you're looking for one, but also, some rules only make sense together and seeing them grouped visually might be helpful. Up to you if you want to alphabetize your rules, here and below

2021-02-27 19:05 UTC, jmuzy-sps commented on portfolio/src/main/webapp/style.css
> +    width: 50%;
Fix indentation so it aligns with the rest of the attributes

2021-02-27 19:05 UTC, jmuzy-sps commented on portfolio/src/main/webapp/style.css
> +.project-description p{
New line between css rules

2021-02-27 19:05 UTC, jmuzy-sps commented on portfolio/src/main/webapp/style.css
> +
Delete extra new line

2021-02-27 19:05 UTC, jmuzy-sps commented on portfolio/src/main/webapp/style.css
> +.project{
Should the rules here and below also have a `main` in front of them? If not, maybe add another comment above `.project` that ends the `/* Main -------- */` comment?

2021-02-28 02:24 UTC, josh-hdz commented on portfolio/src/main/webapp/style.css
> +.project{
I put them there since these rules only apply to objects inside main, but I think it does make more scene for them to be in global since they do have a global scope

2021-02-28 03:00 UTC, jmuzy-sps approved these changes
LGTM, thanks for making the suggested changes!

2021-02-28 03:03 UTC, merged