walkthrough: project-1-servlets
josh-hdz/my_portfolio pull request #5
Opened 2021-03-01 20:29 UTC by josh-hdz

2021-03-01 20:53 UTC, jmuzy-sps requested changes

2021-03-01 20:53 UTC, jmuzy-sps commented on portfolio/src/main/java/com/google/sps/servlets/ServletTest.java
> +/** Handles requests sent to the /hello URL. Try running a server and navigating to /hello! */
Update the comment from "/hello" to "/servlet-test" in both spots

2021-03-01 22:18 UTC, josh-hdz commented on portfolio/src/main/java/com/google/sps/servlets/ServletTest.java
> +/** Handles requests sent to the /hello URL. Try running a server and navigating to /hello! */
I never update the comments but now that you mention it it's really necessary.

2021-03-02 04:51 UTC, jmuzy-sps approved these changes

2021-03-02 04:58 UTC, merged