Walkthough fetch
josh-hdz/my_portfolio pull request #6
Opened 2021-03-01 20:30 UTC by josh-hdz

2021-03-01 20:59 UTC, jmuzy-sps requested changes

2021-03-01 20:59 UTC, jmuzy-sps commented on portfolio/src/main/java/com/google/sps/servlets/ServedDate.java
> +import java.text.SimpleDateFormat;
nit: sort these alphabetically

2021-03-01 20:59 UTC, jmuzy-sps commented on portfolio/src/main/webapp/header-scripts.js
> +function functionManager(){
nit: I don't love the name `functionManager` because it doesn't really tell me what's going on, but I also don't know that I have a better replacement, haha. Maybe `setInitialPageData`?

2021-03-01 22:35 UTC, josh-hdz commented on portfolio/src/main/webapp/header-scripts.js
> +function functionManager(){
What about `setHeaderData`? and also add a description to each function.

2021-03-02 04:53 UTC, jmuzy-sps approved these changes
Good job, thanks for getting those changes in!

2021-03-02 04:58 UTC, merged