Gson integration
josh-hdz/my_portfolio pull request #9
Opened 2021-03-04 22:02 UTC by josh-hdz

2021-03-04 22:46 UTC, jmuzy-sps requested changes
Great job! Mainly just comments about formatting again, functionality-wise you're good!

2021-03-04 22:46 UTC, jmuzy-sps commented on portfolio/src/main/java/com/google/sps/data/HeaderInfo.java
> +        if(size > greetings.length) size = greetings.length;
Optional: I'm personally not a fan of one line if-statements, and at Google we add brackets for these and put the body on a new line. Up to you if you want to change it for your personal portfolio, but I think for group work I will suggest adding brackets for single lines (makes it easier to read imo and easier to add more things to the if later on).

2021-03-04 22:46 UTC, jmuzy-sps commented on portfolio/src/main/java/com/google/sps/servlets/HeaderHandler.java
> +
nit: Delete extra lines

2021-03-04 22:46 UTC, jmuzy-sps commented on portfolio/src/main/java/com/google/sps/data/HeaderInfo.java
> +public final class HeaderInfo{
nit: Here and in the rest of the file - add a space before the bracket `HeaderInfo {`

2021-03-04 22:46 UTC, jmuzy-sps commented on portfolio/src/main/webapp/header-scripts.js
> + * Feches needed info for header and calls needed fucntions to display greeting
nit: spelling - `fetches`, `functions`

2021-03-04 22:46 UTC, jmuzy-sps commented on portfolio/src/main/webapp/header-scripts.js
> +function addRandomGreeting(greetings, last=null) {
Optional and more of just an FYI: Since javascript doesn't require types, it can sometimes be hard to know what the parameters are. You can add what's called JSDoc (https://devhints.io/jsdoc) to your comments, to let readers know what's being passed in, and what the expected return value is. None of this is enforced by a complier, it's just extra info for anyone reading the code, so totally optional if you want to do this or not

2021-03-04 22:46 UTC, jmuzy-sps commented on portfolio/src/main/webapp/header-scripts.js
> + * displays the date on page's header.
nit: captialize "Displays"

2021-03-04 23:44 UTC, josh-hdz commented on portfolio/src/main/webapp/header-scripts.js
> +function addRandomGreeting(greetings, last=null) {
There are some variables that I do not know what type they are like responseFromServer. I will google it and add the documentation.

2021-03-05 03:04 UTC, jmuzy-sps approved these changes

2021-03-05 03:04 UTC, jmuzy-sps commented on portfolio/src/main/webapp/header-scripts.js
> + * @param {array of strings} greetings - greetings to schoose from.
No need to change, just informational, this would be `string[]`

2021-03-05 03:04 UTC, jmuzy-sps commented on portfolio/src/main/webapp/header-scripts.js
> + * @returns None
Also no need to change, just informational - if nothing is returned, then you don't need to add the `@returns` annotation

2021-03-05 03:24 UTC, merged